### ISSUE TITLE
Arduino Nano support? SPI?

### ISSUE THREAD

**Issue by JAndrassy** [ciminaghi/libdfu#2]
Davide, the `esp8266_serial_arduinouno_hacked_interface_ops` doesn't work for Nano with 328p. avrdude uploads to Nano at 57600 baud and the bootloader is different from Uno. Please give me hints how to write dfu_interface_ops & co. for Nano.

**Comment by ciminaghi** [comment]
On Sat, Nov 25, 2017 at 12:57:10PM +0000, Juraj Andr??ssy wrote:
> Davide, the `esp8266_serial_arduinouno_hacked_interface_ops` doesn't work for Nano with 328p. avrdude uploads to Nano at 57600 baud and the bootloader is different from Uno. Please give me hints how to write dfu_interface_ops & co. for Nano. 
>
sorry, I don't know the arduino nano, I'm having a look at the schematic
just now. So you have an external esp8266 module talking to the 328p ?
If the atmega bootloader is different from the one installed on arduino uno,
then maybe the target ops should change too.
If the bootloader has the same protocol and only the baud rate changes 
(115200 -> 57600), then maybe changing

#define DEFAULT_BAUD 115200

to

#define DEFAULT_BAUD 57600

in src/interface/esp8266-serial.c could be the solution.
However, maybe the simplest thing to do is using the spi interface
(esp8266-spi-arduinouno-hacked.cpp). In such case, you can use:

* ESP8266's GPIO5 as target reset wire.
* ESP8266's SPI1 as spi to isp interface

Since esp8266 is a 3.3V part and the 328p is 5V, you should of course setup
some level translation (for my tests I used a simple resistor based voltage
divider for 5->3.3 and an old cmos port for 3.3->5).

Writing custom interface operations shouldn't be too hard.
You can specify 9 methods:

* open -> this is called at startup (you can use it to setup and initialize
the hw).
* write -> this is called by the upper layers when a data buffer has to be
sent to the target.
* read -> this is called by the upper layer to read data received from the
target. It's non blocking (returns -1 if no data is available).
* write_read -> this is to read and write at the same time (spi interfaces
only).
* target_reset -> this is usually invoked at startup to reset the target and
start its bootloader (or generally speaking to put the target into programming
mode)
* target_run -> this is usually invoked after programming has been
successfully completed and let the target run with its new program.
* poll_idle -> this must return DFU_INTERFACE_EVENT when the interface
has some input data ready for being read, or 0 otherwise.
* done -> this is called when the library is done with programming (and before
letting the target run again).
* fini -> this is called after a complete programming cycle has terminated.
Resources allocated in open() can be released here.

You may want to have a look at the files under src/interface for some
real world examples.


Hope this helps
Davide

**Comment by JAndrassy** [comment]
thank you Davide

**Comment by JAndrassy** [comment]
Hi Davide, 
I flashed a Nano connected to esp8266 over SPI with your library using esp8266-spi-arduinouno-hacked.cpp. But it was in a test sketch without other SPI use. But I want to integrate it into WiFi Link firmware. The firmware sets the esp8266 as SPI slave for normal operation and it seems that the master/slave setting remains after Atmega reset for flashing. I see in esp8266-spi-arduinounowifiv8.cpp that it was somehow solved using pin 16, but without a schema of the V8 it is not clear how.
Did you solved this for Primo?

**Comment by ciminaghi** [comment]
On Wed, Jan 24, 2018 at 02:08:54PM +0000, Juraj Andr??ssy wrote:
> Hi Davide, 
> I flashed a Nano connected to esp8266 over SPI with your library using esp8266-spi-arduinouno-hacked.cpp. But it was in a test sketch without other SPI use. But I want to integrate it into WiFi Link firmware. The firmware sets the esp8266 as SPI slave for normal operation and it seems that the master/slave setting remains after Atmega reset for flashing. I see in esp8266-spi-arduinounowifiv8.cpp that it was somehow solved using pin 16, but without a schema of the V8 it is not clear how.

Oops this is old stuff, I can't find a v8 schematic too. If I remember well,
the problem on the uno was that the atmega was 5V, while the esp8266
was 3.3. So we had some bidirectional buffer and level translator controlled
by gpio 16.

As far as I can remember, though, just before entering production they
changed the schematic to save space/money and the buffers disappeared.
gpio16 is still mentioned in libdfu, but it's actually dummy (and I didn't
change my sources because I actually don't have any unowifi-v8 production
board to test, as far as I can remember). I was told that the board should
work ok even without buffers, anyway (somebody else did the tests).

> Did you solved this for Primo?

the primo is different, because both chips are 3.3V, and you don't need
any voltage translators in between. So we shouldn't have this problem
(even if I'm actually facing many others with uploading signed nordic images,
not exactly simple :-)

Davide

**Comment by JAndrassy** [comment]
If I add `SPISlave.begin();` to the test sketch `setup()`, the dfu can't sync with Atmega. it doesn't help when I move `esp8266_spi_open()` from `esp8266_arduinouno_hacked_spi_open()` to `esp8266_spi_arduinouno_hacked_target_reset()`. something stays from the slave setup. I think with Primo it will be the same problem, because it is a problem of the esp8266 side.

**Comment by ciminaghi** [comment]
On Wed, Jan 24, 2018 at 05:13:04PM +0000, Juraj Andr??ssy wrote:
> If I add `SPISlave.begin();` to the test sketch `setup()`, the dfu can't sync with Atmega. it doesn't help when I move `esp8266_spi_open()` from `esp8266_arduinouno_hacked_spi_open()` to `esp8266_spi_arduinouno_hacked_target_reset()`. something stays from the slave setup.

typo, master setup ?

Sorry, there's something I can't understand here. If you move
esp8266_spi_open() to target reset, the spi will be reopened as
a master, so that can't fix things as far as I can see. After progremming
the atmega, you want the esp8266 to be slave, right ?
Or am I missing something ?

> I think with Primo it will be the same problem, because it is a problem of the esp8266 side.
>
My understanding was that you were talking about gpios controlling
bidirectional buffers, which we don't have on the Primo.

I don't know. But there's nothing actually magic in this: esp8266_spi_open()
(which is the generic open for esp8266) just sets up the esp8266 as __master__.
To go back to slave mode, you just have to reconfigure it as a slave.
Then the board-specific open does board-specific things, so typically
configures and sets gpios to some value. This can be reversed, just do the
opposite of what is done in the board-specific open.

If this still is not enough, there's some other problem. For instance (just
random ideas, not sure about anything): the atmega is held in reset, so you
can't talk to it because it's dead. Or something is missing in
SPISlave.begin(), so that it works when you wake up from reset (because the
reset value of some register is ok), but it doesn't work anymore
when you re-configure the port coming from master mode. Or again, libdfu has
actually [temporarily] "bricked" the atmega because of some bug.

What I'm pretty sure about, is that you should definitely be able to reverse
the spi configuration from slave to master and back with no problem. If you 
send me your sketch I can have a look at it and see if I have some more
ideas. What I can't do at the moment is actual testing, because I'm very
busy with the Primo and other things (but if you're patient enough I may
have some time in the next weeks).

Thanks
Davide

**Comment by JAndrassy** [comment]
DfuTest.ino
```
#include <ESP8266WiFi.h>
#include <WiFiManager.h>
#include <ESP8266mDNS.h>
#include <ESP8266WebServer.h>
#include <SPISlave.h>

ESP8266WebServer webServer(80);

void setup()
{
  Serial.begin(115200);
  MDNS.begin("arduino");
  MDNS.enableArduino(80);

  WiFiManager wifiManager;
  wifiManager.autoConnect();

  Serial.flush();

  _setup_dfu();

  SPISlave.begin(); // without this dfu works

  webServer.begin();
}

void loop()
{
  webServer.handleClient();
  _handle_Mcu_OTA();
}
```

**Comment by jandrassy** [comment]
ArduinoMcuOTA.ino
```
#include <dfu.h>
#include <dfu-host.h>
#include <dfu-cmd.h>
#include <user_config.h>
#include <dfu-internal.h>
#include <dfu-esp8266.h>
#include <dfu-avrisp.h>

struct dfu_data *global_dfu;
struct dfu_binary_file *global_binary_file;

static int _setup_dfu(void)
{
global_dfu = dfu_init(&esp8266_spi_arduinouno_hacked_interface_ops,
              NULL,
              NULL,
              NULL,
              NULL,
              &avrisp_dfu_target_ops,
              &atmega328p_device_data,
              &esp8266_dfu_host_ops);

  if (!global_dfu) {
    /* FIXME: Is this ok ? */
    return -1;
  }

  global_binary_file = dfu_binary_file_start_rx(&dfu_rx_method_http_arduino, global_dfu, &webServer);
  if (!global_binary_file) {
    return -1;
  }

  if (dfu_binary_file_flush_start(global_binary_file) < 0) {
      return -1;
  }
  return 0;
}

void _finalize_dfu(void)
{
  dfu_binary_file_fini(global_binary_file);
  dfu_fini(global_dfu);
  global_dfu = NULL;
  global_binary_file = NULL;
}

void _handle_Mcu_OTA(void)
{
   if (!global_dfu)
     _setup_dfu();
   if (!global_dfu)
     return;
   switch (dfu_idle(global_dfu)) {
    case DFU_ERROR:
      _finalize_dfu();
      break;
    case DFU_ALL_DONE:
      dfu_target_go(global_dfu);
      _finalize_dfu();
      delay(80);
      break;
    case DFU_CONTINUE:
      break;
    }
}
```

**Comment by JAndrassy** [comment]
I was referring to comments about pin 16 in [esp8266-spi-arduinounowifiv8.cpp](https://github.com/ciminaghi/libdfu/blob/arduino-debug/src/interface/esp8266-spi-arduinounowifiv8.cpp)
```
 * Arduino unowifi v8: uses SPI direct esp8266 <-> atmega328
 * connection, GPIO4 for target reset, UART0 as a serial console,
 * GPIO16 (XPD-DCDC) for setting SPI direction (low -> esp8266 is master)
```

**Comment by ciminaghi** [comment]
On Wed, Jan 24, 2018 at 06:35:11PM +0000, Juraj Andr??ssy wrote:
> DfuTest.ino
>

Hi,

comments below.

 ```
> #include <ESP8266WiFi.h>
> #include <WiFiManager.h>
> #include <ESP8266mDNS.h>
> #include <ESP8266WebServer.h>
> #include <SPISlave.h>
> 
> ESP8266WebServer webServer(80);
> 
> void setup()
> {
>   Serial.begin(115200);
>   MDNS.begin("arduino");
>   MDNS.enableArduino(80);
> 
>   WiFiManager wifiManager;
>   wifiManager.autoConnect();
> 
>   Serial.flush();
> 
>   _setup_dfu();
> 
>   SPISlave.begin(); // without this dfu works

well: as you call this, SPI gets configured in slave mode, so dfu cannot
work anymore (the comment is correct :-).
If I have understood, you'd like to have a sketch which can
both program the atmega (esp8266 spi in master mode) and do something else for
the rest of the time (esp8266 spi in slave mode). To do this, you need to
clearly separate the two working modes. For example you can start normally,
with spi in slave mode, then some event will make you switch to dfu (and at
that moment you call _setup_dfu()), and when dfu is over you reinitialize
the spi in slave mode, and so on.

For instance:

int in_dfu = 0;

void setup()
{
	Serial.begin(115200);
	MDNS.begin("arduino");
	MDNS.enableArduino(80);

	WiFiManager wifiManager;
	wifiManager.autoConnect();

	Serial.flush();
	// Start as spi slave
	SPISlave.begin();
	webServer.begin();
}

// Now assume you have a callback which is invoked when you want to switch
// from normal to dfu mode:

void switch_to_dfu()
{
	in_dfu = 1;
	// This sets up the spi port as master
	_setup_dfu();
}

// And another callback when going from dfu to normal
void switch_to_normal()
{
	in_dfu = 0;
	// spi back to slave
	SPISlave.begin();
	// and maybe play more gpio games in here ....
	// ....
}

loop()
{
	webServer.handleClient();
	if (in_dfu)
		_handle_Mcu_OTA();
	else
		do_something_else();
}

The only problem is finding a way for calling the two switch_ callbacks, but
that's related to your application, so I guess it could be done in many
different ways.

The important thing is that spi cannot be master and slave at the same
time, so calling SPISlave.begin() and _setup_dfu() one after the other
will probably not work (whoever is called last wins, you can't be master
and slave at the same time).

Davide

**Comment by ciminaghi** [comment]
On Wed, Jan 24, 2018 at 08:29:11PM +0000, Juraj Andr??ssy wrote:
> I was referring to comments about pin 16 in [esp8266-spi-arduinounowifiv8.cpp](https://github.com/ciminaghi/libdfu/blob/arduino-debug/src/interface/esp8266-spi-arduinounowifiv8.cpp)
> ```
>  * Arduino unowifi v8: uses SPI direct esp8266 <-> atmega328
>  * connection, GPIO4 for target reset, UART0 as a serial console,
>  * GPIO16 (XPD-DCDC) for setting SPI direction (low -> esp8266 is master)
>
spi direction refers to the fact that there was a bidirectional buffer
and voltage translator between the esp8266 (3.3V) and the atmega (5V).
While programming the atmega, the esp8266 becomes master, so MOSI is an
output for the esp8266 and an input for the atmega:

       	       	    MOSI
                3.3          5
       ESP8266 ----- >  --------- ATMEGA

On the other hand, in "normal" mode, the atmega is master, so it drives MOSI:

                3.3        5
       ESP8266 ----- < ---------- ATMEGA

MISO is the same thing, but the other way around (i.e. the ESP8266 drives
MISO in normal mode). GPIO16 was used to control buffer direction.

In production, I think the buffer was replaced by something else, so GPIO16
is now dummy.

Davide

**Comment by JAndrassy** [comment]
Thank you for the explanation of the pin 16. Now I understand, that it is irrelevant to this problem.

I made improvements for Uno WiFi Dev Ed and to WiFi Link Serial mode including MCU OTA for 328p with Optiboot. 
And then I just of curiosity tested WiFi Link with SPI connected Wemos and Nano and it worked.  So next step would by to have MCU OTA with SPI connected WiFi Link. It looks like it could work, if the SPI modes switching can be solved. I hoped you solved it already for Primo.

On Primo the WiFi Link is used too. So if Primo should have MCU OTA, then this esp8266 SPI client/master switching must be solved in WiFi Link for Primo too, I think.

**Comment by JAndrassy** [comment]
Hi Davide. After our discussion here in January I coded SPISlave.end() for the esp8266 SPISlave library and 'pullrequested' it. It didn't make it into 2.4.1 version in March, but is now in the 2.4.2 esp8266 core package. So switching SPI between slave and master is now possible.

**Comment by ciminaghi** [comment]
nice, thanks for the update.

I did some work on the primo to allow OTA of the nrf52 via wifi (see https://github.com/ciminaghi/libdfu/tree/nordic-dfu1). Code is currently still under test, I'm also writing  an arduino sample sketch (test program is currently in C, see https://github.com/ciminaghi/libdfu/blob/nordic-dfu1/samples/esp8266-arduinoprimo-nordic.c).

Davide
